language: scala
script: sbt 'set envVars:=Map("APPLICATION_SECRET"->"a","GOOGLE_CLIENT_ID"->"a","GOOGLE_CLIENT_SECRET"->"a","WITH_TEST_DATA"->"true")' ++$TRAVIS_SCALA_VERSION scoverage:test coveralls
scala:
  - "2.10.3"
jdk:
  - oraclejdk7
  - openjdk7
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
# whitelist
branches:
  only:
    - master
