from adaptorel/u14.04_play-2.2.3

RUN git clone https://github.com/adaptorel/oauthorize.git

WORKDIR /oauthorize

RUN /opt/play/play clean stage

ENTRYPOINT target/universal/stage/bin/oauthorize-play-2-2